ModeShape/modeshape

web/modeshape-web-cmis-war/src/test/java/org/modeshape/cmis/ModeShapeCmisClientTest.java
web/modeshape-web-cmis/src/main/java/org/modeshape/cmis/JcrMsVersion.java
web/modeshape-web-cmis/src/main/java/org/modeshape/cmis/JcrMsVersionNode.java
web/modeshape-web-cmis/src/main/java/org/modeshape/cmis/JcrServiceFactory.java
web/modeshape-web-cmis/src/main/java/org/modeshape/cmis/MsDocumentTypeHandler.java

This PR contains:
- Fix for the error accessing previous versions of the document;
- Test case for this scenario

MODE-2367:Error to access contents of older versions via CMIS

---

web/modeshape-web-cmis-war/src/test/java/org/modeshape/cmis/ModeShapeCmisClientTest.java
web/modeshape-web-cmis/src/main/java/org/modeshape/cmis/JcrMsVersion.java
web/modeshape-web-cmis/src/main/java/org/modeshape/cmis/MsDocumentTypeHandler.java

This PR introduces cmis:contentStreamHash property

MODE-2360: Add content hash property

---

sequencers/modeshape-sequencer-ddl/src/main/java/org/modeshape/sequencer/ddl/dialect/oracle/OracleDdlConstants.java
sequencers/modeshape-sequencer-ddl/src/main/java/org/modeshape/sequencer/ddl/dialect/oracle/OracleDdlParser.java
sequencers/modeshape-sequencer-ddl/src/test/java/org/modeshape/sequencer/ddl/dialect/oracle/OracleDdlParserTest.java

Added support for multiple ADD/MODIFY clauses in ALTER TABLE
statements and some minor changes to MODE-2350

MODE-2439 Oracle DDL parser enhacement

---

modeshape-parent/pom.xml
web/modeshape-web-explorer/pom.xml
web/modeshape-web-explorer/src/main/java/org/modeshape/web/Console.gwt.xml
web/modeshape-web-explorer/src/main/java/org/modeshape/web/client/AdminView.java
web/modeshape-web-explorer/src/main/java/org/modeshape/web/client/JcrService.java
web/modeshape-web-explorer/src/main/java/org/modeshape/web/client/JcrServiceAsync.java
web/modeshape-web-explorer/src/main/java/org/modeshape/web/client/chart/Chart.java
web/modeshape-web-explorer/src/main/java/org/modeshape/web/server/JcrServiceImpl.java
web/modeshape-web-explorer/src/main/java/org/modeshape/web/server/impl/MsDurationMetric.java
web/modeshape-web-explorer/src/main/java/org/modeshape/web/server/impl/MsValueMetric.java
web/modeshape-web-explorer/src/main/java/org/modeshape/web/server/impl/TimeUnit.java
web/modeshape-web-explorer/src/main/java/org/modeshape/web/shared/DurationParameter.java
web/modeshape-web-explorer/src/main/java/org/modeshape/web/shared/Stats.java

This PR implements charts for the repository metrcis

MODE-2235: Web-explorer should show metrics

---

web/modeshape-web-explorer/pom.xml
web/modeshape-web-explorer/src/main/java/org/modeshape/web/BackupExportServlet.java
web/modeshape-web-explorer/src/main/java/org/modeshape/web/BackupUploadServlet.java
web/modeshape-web-explorer/src/main/java/org/modeshape/web/client/JcrService.java
web/modeshape-web-explorer/src/main/java/org/modeshape/web/client/JcrServiceAsync.java
web/modeshape-web-explorer/src/main/java/org/modeshape/web/client/admin/AdminView.java
web/modeshape-web-explorer/src/main/java/org/modeshape/web/client/admin/BackupControl.java
web/modeshape-web-explorer/src/main/java/org/modeshape/web/client/admin/BackupDialog.java
web/modeshape-web-explorer/src/main/java/org/modeshape/web/client/admin/BackupDownloadControl.java
web/modeshape-web-explorer/src/main/java/org/modeshape/web/client/admin/BackupOptionsDialog.java
web/modeshape-web-explorer/src/main/java/org/modeshape/web/client/admin/RestoreControl.java
web/modeshape-web-explorer/src/main/java/org/modeshape/web/client/admin/UploadBackupDialog.java
web/modeshape-web-explorer/src/main/java/org/modeshape/web/server/JcrServiceImpl.java
web/modeshape-web-explorer/src/main/java/org/modeshape/web/server/LRepository.java
web/modeshape-web-explorer/src/main/java/org/modeshape/web/server/impl/BackupUsrOptions.java
web/modeshape-web-explorer/src/main/java/org/modeshape/web/server/impl/ConnectorImpl.java
web/modeshape-web-explorer/src/main/java/org/modeshape/web/server/impl/JsonConfigConnectorImpl.java
web/modeshape-web-explorer/src/main/java/org/modeshape/web/server/impl/LRepositoryImpl.java
web/modeshape-web-explorer/src/main/java/org/modeshape/web/server/impl/RestoreUsrOptions.java
web/modeshape-web-explorer/src/main/java/org/modeshape/web/shared/BackupParams.java
web/modeshape-web-explorer/src/main/java/org/modeshape/web/shared/RestoreParams.java

This PR contains the following changes:
- backup/restore dialogs with process parameters;
- backup/restore process moved into servlet's temporary directory.

MODE-2443-b: Enhance backup/restore process for the web explorer.

---

web/modeshape-web-explorer/src/main/java/org/modeshape/web/server/impl/TimeUnit.java

Sorry for the huge amount of PR...

Changed timeunits' names to better reflect their definition

---

sequencers/modeshape-sequencer-ddl/src/main/java/org/modeshape/sequencer/ddl/dialect/teiid/AlterOptionsParser.java
sequencers/modeshape-sequencer-ddl/src/main/java/org/modeshape/sequencer/ddl/dialect/teiid/TeiidDdlLexicon.java
sequencers/modeshape-sequencer-teiid/src/main/java/org/modeshape/sequencer/teiid/VdbSequencer.java

Problems/omissions encountered during debugging of the sequencers in development of VdbBuilder/komodo.

Small Sequencer Fixes found during testing

---

modeshape-jcr/src/main/java/org/modeshape/jcr/txn/Transactions.java

This is a forward-port of the existing fix.

MODE-2493 Fixed the rollback handling of ModeShape transactions.

---

web/modeshape-web-explorer/src/main/java/org/modeshape/web/client/contents/RefreshSessionDialog.java

This PR is just a simple fix for a dialog window.

MODE-2467: Modeshape-explorer: add mixin when clicking refresh.

---

modeshape-jcr-api/src/main/java/org/modeshape/jcr/api/query/QueryManager.java
modeshape-jcr/src/main/java/org/modeshape/jcr/ExecutionContext.java
modeshape-jcr/src/main/java/org/modeshape/jcr/JcrQueryManager.java
modeshape-jcr/src/main/java/org/modeshape/jcr/value/ValueComparators.java
modeshape-jcr/src/main/java/org/modeshape/jcr/value/ValueTypeSystem.java
modeshape-jcr/src/test/java/org/modeshape/jcr/JcrQueryManagerTest.java

This will be used in turn when performing string comparisons.

MODE-1727 Allows the possibility of setting a custom Locale instance when querying

---

modeshape-jcr/src/main/java/org/modeshape/jcr/JcrSession.java
modeshape-jcr/src/main/java/org/modeshape/jcr/cache/SessionCache.java
modeshape-jcr/src/main/java/org/modeshape/jcr/cache/document/WritableSessionCache.java

This is the porting of https://github.com/ModeShape/modeshape/pull/1483 for `master`

MODE-2530 Fixes the potential corruption of the version history structure for a versionable node under concurrent access

---

modeshape-jcr/src/main/java/org/modeshape/jcr/NodeTypes.java
modeshape-jcr/src/main/java/org/modeshape/jcr/cache/document/WritableSessionCache.java
modeshape-jcr/src/test/java/org/modeshape/jcr/JcrNodeTest.java
modeshape-jcr/src/test/java/org/modeshape/jcr/LocalIndexProviderTest.java
modeshape-jcr/src/test/resources/cnd/nodetypes-with-sns.cnd

Forward porting of: https://github.com/ModeShape/modeshape/pull/1485

MODE-2533 Fixes the logic which determines whether a node type allows SNS or not

---

sequencers/modeshape-sequencer-ddl/src/main/java/org/modeshape/sequencer/ddl/dialect/teiid/CreateProcedureParser.java
sequencers/modeshape-sequencer-ddl/src/main/java/org/modeshape/sequencer/ddl/dialect/teiid/StatementParser.java
sequencers/modeshape-sequencer-ddl/src/main/resources/org/modeshape/sequencer/ddl/dialect/teiid/TeiidDdl.cnd
sequencers/modeshape-sequencer-ddl/src/test/java/org/modeshape/sequencer/ddl/dialect/teiid/CreateProcedureParserTest.java
sequencers/modeshape-sequencer-ddl/src/test/java/org/modeshape/sequencer/ddl/dialect/teiid/TeiidDdlSequencerTest.java
sequencers/modeshape-sequencer-ddl/src/test/resources/ddl/dialect/teiid/resultSetOptions.ddl

- changed parser to handle options for result sets.
- added parser and sequencer tests.

MODE-2508 Add OPTIONS capability to Procedure ResultSet

---

boms/modeshape-bom-embedded/pom.xml
checkstyle/pom.xml
checkstyle/src/main/java/org/modeshape/checkstyle/JavaDocUtil.java
checkstyle/src/main/java/org/modeshape/checkstyle/UnusedImports.java
deploy/jbossas/kit/jboss-wf/standalone/configuration/standalone-modeshape-ha.xml
integration/modeshape-jbossas-integration-tests/pom.xml
integration/modeshape-jbossas-integration-tests/src/test/resources/arquillian.xml
integration/modeshape-jbossas-kit-tests/pom.xml
integration/modeshape-jbossas-kit-tests/src/test/resources/arquillian.xml
modeshape-assembly-descriptors/src/main/resources/assemblies/jboss-wf-dist.xml
modeshape-distribution/pom.xml
modeshape-jcr/src/main/java/org/modeshape/jcr/clustering/ClusteringService.java
modeshape-parent/pom.xml
persistence/modeshape-persistence-relational/src/test/resources/db-config-h2-full.json
persistence/modeshape-persistence-relational/src/test/resources/db-config.json

It also makes some build changes removing/renaming some properties.

MODE-2543 Updates to jboss-parent 20 (JDK 8).

---

web/modeshape-web-explorer/src/main/java/org/modeshape/web/client/contents/PermissionsEditor.java
web/modeshape-web-explorer/src/main/java/org/modeshape/web/server/JcrServiceImpl.java

This PR handles case when user has no permission to read access control content. In this case access list is not displayed rather then exception is thrown.

MODE-2535: Readonly user is not allowed in Web Explorer

---

deploy/jbossas/kit/jboss-wf/org/modeshape/index-provider/elasticsearch/main/module.xml
index-providers/modeshape-elasticsearch-index-provider/pom.xml
index-providers/modeshape-elasticsearch-index-provider/src/main/java/org/modeshape/jcr/index/elasticsearch/client/EsClient.java
index-providers/modeshape-elasticsearch-index-provider/src/test/java/org/modeshape/jcr/index/elasticsearch/client/EsClientTest.java

This PR replaces simple http connections with Apache Http client library.

MODE-2588: ElasticSearch Index Provider. BindException

---

modeshape-jcr/src/main/java/org/modeshape/connector/filesystem/FileSystemConnector.java

addresses [MODE-2601](https://issues.jboss.org/browse/MODE-2601)

MODE-2601 enable configurable node handling by FileSystemConnector subclasses

---

modeshape-jcr/src/main/java/org/modeshape/jcr/JcrRepository.java
modeshape-jcr/src/test/java/org/modeshape/jcr/JcrRepositoryTest.java

Related to: https://issues.jboss.org/browse/MODE-2603

Initial time expression bug

---

.travis.yml
README.md

The build just runs `mvn -s settings.xml clean install -Pintegration`

MODE-2599 Added Travis-CI build

---

connectors/modeshape-connector-cmis/src/main/java/org/modeshape/connector/cmis/AclObjectId.java
connectors/modeshape-connector-cmis/src/main/java/org/modeshape/connector/cmis/CmisConnector.java
connectors/modeshape-connector-cmis/src/main/java/org/modeshape/connector/cmis/Converter.java
connectors/modeshape-connector-cmis/src/main/java/org/modeshape/connector/cmis/ObjectId.java
connectors/modeshape-connector-cmis/src/main/java/org/modeshape/connector/cmis/Properties.java
connectors/modeshape-connector-cmis/src/test/java/org/modeshape/connector/cmis/CmisConnectorIT.java

This PR allows to read access lists defined by CMIS repository.

MODE-2094: Access list support fot CMIS connector

---

web/modeshape-web-explorer/src/main/java/org/modeshape/web/client/JcrService.java
web/modeshape-web-explorer/src/main/java/org/modeshape/web/client/JcrServiceAsync.java
web/modeshape-web-explorer/src/main/java/org/modeshape/web/client/contents/ChildrenEditor.java
web/modeshape-web-explorer/src/main/java/org/modeshape/web/client/grid/Grid.java
web/modeshape-web-explorer/src/main/java/org/modeshape/web/client/grid/Pager.java
web/modeshape-web-explorer/src/main/java/org/modeshape/web/server/JcrServiceImpl.java
web/modeshape-web-explorer/src/main/java/org/modeshape/web/shared/JcrNode.java
web/modeshape-web-explorer/src/main/resources/META-INF/resources/Console.css

This PR adds pager for the list of child nodes

MODE-2513: Add pager for node list in Web-explorer

---

modeshape-jcr/src/test/java/org/modeshape/jcr/ClusteringHelper.java

I've revised the commit per your suggestions.

Resolves https://issues.jboss.org/browse/MODE-2622:

---

modeshape-jcr/src/main/java/org/modeshape/jcr/cache/document/WritableSessionCache.java
modeshape-jcr/src/test/java/org/modeshape/jcr/TransactionsTest.java

Each workspace cache should be cleared individually when a transaction commits. The previous code only cleared the first ws cache which registered a transaction synchronization

MODE-2627 Fixes additional transactional issues around the workspace cache

---

boms/modeshape-bom-embedded/pom.xml
boms/modeshape-bom-jbossas/pom.xml
deploy/jbossas/modeshape-jbossas-subsystem/src/main/java/org/modeshape/jboss/subsystem/AddMongoBinaryStorage.java

In addition, adds the Java drivers for Mongo, Cassandra and S3 to the BOMs

MODE-2628 Fixes the MongoDB configuration in the WF kit

---

modeshape-jcr/src/main/java/org/modeshape/jcr/JcrLockManager.java
modeshape-jcr/src/main/java/org/modeshape/jcr/RepositoryLockManager.java
modeshape-jcr/src/test/java/org/modeshape/jcr/JcrLockManagerTest.java

The previous code did no take into account that depending on the timeout setting, a session or an open scoped lock may be expired and still be present on a node.

MODE-2633 Fixes the handling of lock expiration

---

modeshape-jcr/src/main/java/org/modeshape/jcr/BackupService.java
modeshape-jcr/src/test/java/org/modeshape/jcr/RepositoryBackupAndRestoreTest.java
modeshape-jcr/src/test/java/org/modeshape/jcr/TestingUtil.java

MODE-2611 Fixes the duplicate export of repository metadata in the backup file

MODE-2611 backported to 4.6.2

---

modeshape-jcr-api/src/main/java/org/modeshape/jcr/api/BackupOptions.java
modeshape-jcr/src/main/java/org/modeshape/jcr/BackupService.java

MODE-2587 Updates backup to perform the operation in batches.
* Note, only the backup half of the original PR has been ported, not the restore.
Depends on: https://github.com/ModeShape/modeshape/pull/1603

MODE-2587 to 4.6.2

---

modeshape-jcr/src/main/java/org/modeshape/jcr/query/model/SelectorName.java

https://issues.jboss.org/browse/MODE-2649

support non-built-in namespaces in query selectors

---

connectors/modeshape-connector-git/src/main/java/org/modeshape/connector/git/GitTree.java
connectors/modeshape-connector-git/src/test/java/org/modeshape/connector/git/GitConnectorTest.java

The previous code attempted to store binaries for large files into the repository's binary store which is not possible outside of a transaction. In general, connectors should always return external binaries which are resolved by the external system "on demand"

MODE-2643 Changes the GitConnector's logic so that it always returns external binaries

---

modeshape-jcr/src/main/java/org/modeshape/jcr/value/binary/MongodbBinaryStore.java

based on the patches provided on the [MODE-2663](https://issues.jboss.org/browse/MODE-2663) with slight modifications

MODE-2663 Adds ordering to the MongoDB input/output stream chunks so that they work with Mongo replicas

---

modeshape-parent/pom.xml
modeshape-persistence-tests/pom.xml
persistence/modeshape-persistence-relational/src/main/java/org/modeshape/persistence/relational/DefaultStatements.java
persistence/modeshape-persistence-relational/src/main/java/org/modeshape/persistence/relational/RelationalDb.java
persistence/modeshape-persistence-relational/src/main/java/org/modeshape/persistence/relational/RelationalDbConfig.java
persistence/modeshape-persistence-relational/src/main/java/org/modeshape/persistence/relational/RelationalProviderI18n.java
persistence/modeshape-persistence-relational/src/main/java/org/modeshape/persistence/relational/SQLServerStatements.java
persistence/modeshape-persistence-relational/src/main/resources/org/modeshape/persistence/relational/RelationalProviderI18n.properties
persistence/modeshape-persistence-relational/src/main/resources/org/modeshape/persistence/relational/sqlserver_database.properties
persistence/modeshape-persistence-relational/src/test/resources/db-config.json

The fixes include:
* making sure CREATE and DROP table statements correctly detect existing objects
* using correct syntax for DB locking
* using the correct binary type for storing schematic documents

MODE-2664 Fixes various issues with SQLServer support

---

connectors/modeshape-connector-jdbc-metadata/src/main/java/org/modeshape/connector/meta/jdbc/DatabaseRetriever.java
modeshape-common/src/main/java/org/modeshape/common/text/TokenStream.java
modeshape-jcr/src/main/java/org/modeshape/jcr/CndImporter.java
modeshape-jcr/src/main/java/org/modeshape/jcr/JcrRepository.java
modeshape-jcr/src/test/java/org/modeshape/jcr/JcrRepositoryTest.java
sequencers/modeshape-sequencer-ddl/src/main/java/org/modeshape/sequencer/ddl/dialect/oracle/OracleDdlParser.java
sequencers/modeshape-sequencer-video/src/main/java/org/modeshape/sequencer/video/VideoMetadata.java

This affects node types and any other places where the aforementioned class is used

MODE-2679 Fixes case insensitive comparisons done via the TokenStream

---

modeshape-jcr/src/main/java/org/modeshape/jcr/index/local/LocalDuplicateIndex.java

This change should make the logic fault-tolerant when the index is stopped unexpectedly

MODE-2681 Fixes the updating of the counter for the local duplicate index

---

index-providers/modeshape-lucene-index-provider/src/test/java/org/modeshape/jcr/index/lucene/LuceneIndexProviderTest.java
modeshape-jcr/src/main/java/org/modeshape/jcr/index/local/LocalEnumeratedIndex.java
modeshape-jcr/src/test/java/org/modeshape/jcr/AbstractIndexProviderTest.java

This change first makes sure that the total index count is calculated in memory and also uses the MapDB internal counter for the inner hash sets

MODE-2682 Fixes the performance issues with the LocalEnumeratedIndex

---

persistence/modeshape-persistence-relational/src/main/java/org/modeshape/persistence/relational/DB2Statements.java
persistence/modeshape-persistence-relational/src/main/java/org/modeshape/persistence/relational/DataSourceManager.java
persistence/modeshape-persistence-relational/src/main/java/org/modeshape/persistence/relational/RelationalDb.java
persistence/modeshape-persistence-relational/src/main/resources/org/modeshape/persistence/relational/db2_database.properties

(cherry picked from commit 3dc6b28)

MODE-2687: DB2 Support

---

modeshape-jcr/src/main/java/org/modeshape/jcr/value/binary/S3BinaryStore.java

https://issues.jboss.org/browse/MODE-2690

[MODE-2690] Set content length in ObjectMetadata for S3 uploads

---

modeshape-jcr/src/main/java/org/modeshape/jcr/value/binary/S3BinaryStore.java

https://issues.jboss.org/browse/MODE-2691

[MODE-2691] Set min size of S3BinaryStore's file system cache to 0

---

modeshape-jcr/src/main/java/org/modeshape/jcr/value/binary/S3BinaryStore.java
modeshape-jcr/src/test/java/org/modeshape/jcr/value/binary/S3BinaryStoreTest.java

https://issues.jboss.org/browse/MODE-2692

[MODE-2692] Return null MIME type in case of "application/octet-stream"

---

modeshape-jcr/src/main/java/org/modeshape/jcr/mimetype/tika/TikaNameOnlyDetector.java

https://issues.jboss.org/browse/MODE-2694

[MODE-2694] Close input streams passed to TikaNameOnlyDetector.detect()

---

persistence/modeshape-persistence-file/src/main/java/org/modeshape/persistence/file/FileDb.java

See https://issues.jboss.org/browse/MODE-2728

MODE-2728 Fixes transaction leak in FileDb
