ModeShape/modeshape

- modeshape-jcr/src/main/java/org/modeshape/jcr/AccessControlManagerImpl.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/security/acl/AccessControlEntryImpl.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/security/acl/JcrAccessControlList.java
- modeshape-jcr/src/test/java/org/modeshape/jcr/security/AccessControlManagerTest.java
- modeshape-jcr/src/test/java/org/modeshape/jcr/security/acl/AccessControlPolicyIteratorImplTest.java
- modeshape-jcr/src/test/java/org/modeshape/jcr/security/acl/JcrAccessControlListTest.java
If a node has empty ACLs, then the nearest non-empty ones in the hierarchy should be taken into account instead of assuming all permissions are granted on that node.
> MODE-2408 Fixed the handling of empty ACLs

- modeshape-jcr/src/main/java/org/modeshape/jcr/bus/BusI18n.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/bus/ClusteredChangeBus.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/clustering/ClusteringService.java
- modeshape-jcr/src/main/resources/org/modeshape/jcr/bus/BusI18n.properties
- modeshape-jcr/src/test/java/org/modeshape/jcr/ClusteredRepositoryTest.java
- modeshape-jcr/src/test/java/org/modeshape/jcr/bus/AbstractChangeBusTest.java
This is the only way (apart from not sending loopback messages through JGroups) to ensure that when a thread calls `bus.notify` all the "in-thread" listeners have actually been notified before continuing with that thread. This in turn is a precondition that must hold true for any changes in the system area to work correctly.
> MODE-2409 Changed the ClusteredChangeBus to wait until it receives loopback-changesets.

- modeshape-jcr/src/main/java/org/modeshape/jcr/JcrI18n.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/value/binary/Database.java
- modeshape-jcr/src/main/resources/org/modeshape/jcr/JcrI18n.properties
- modeshape-jcr/src/main/resources/org/modeshape/jcr/database/binary_store_h2_database.properties
- modeshape-jcr/src/test/java/org/modeshape/jcr/value/binary/DatabaseBinaryStoreTest.java
- modeshape-parent/pom.xml
If the length of the text is larger than the size of the DB column, it will be trimmed.
> MODE-2412 Fixed the handling of large extracted text values for the database binary stores

- boms/modeshape-bom-embedded/pom.xml
- boms/modeshape-bom-jbossas/pom.xml
- deploy/jbossas/kit/jboss-wf8/org/modeshape/main/module.xml
- deploy/jbossas/modeshape-jbossas-subsystem/pom.xml
- deploy/jbossas/modeshape-jbossas-subsystem/src/main/java/org/modeshape/jboss/security/JBossDomainAuthenticationProvider.java
- deploy/jbossas/modeshape-jbossas-subsystem/src/main/java/org/modeshape/jboss/service/RepositoryService.java
- deploy/jbossas/modeshape-jbossas-subsystem/src/main/java/org/modeshape/jboss/subsystem/AddRepository.java
- integration/modeshape-jbossas-integration-tests/src/test/java/org/modeshape/test/integration/SecurityIntegrationTest.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/JcrRepository.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/RepositoryConfiguration.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/security/EnvironmentAuthenticationProvider.java
- modeshape-parent/pom.xml
This should make sure whatever caching is configured via the container is being leveraged by ModeShape.
> MODE-2411 Extended the default JAAS provider to be able to interact with the JBoss container's SecurityManagementService.

- modeshape-jcr/src/main/java/org/modeshape/jcr/AbstractJcrNode.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/JcrI18n.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/JcrVersionManager.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/document/LocalDocumentStore.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/document/WritableSessionCache.java
- modeshape-jcr/src/main/resources/org/modeshape/jcr/JcrI18n.properties
- modeshape-jcr/src/test/java/org/modeshape/jcr/ConcurrentWriteTest.java
- modeshape-schematic/src/main/java/org/infinispan/schematic/internal/SchematicEntryLiteral.java
This PR contains 2 commits:
- one which adds a small optimization & a better exception message for the `JcrVersionManager`
- one which fixes a potentially much more critical issue: when using local transactions (i.e. started & committed by ModeShape during session.save) there was a potential leakage of nodes that were being changed/edited in that transaction into the shared workspace cache (used by everyone else incl. readers), __before the transaction was committed__ The solution was to make sure that a `TransactionalWorkspaceCache` is used *always*, regardless whether a user or a local transaction in active.
> MODE-2418 Fixed potential ConcurrentModificationException

- modeshape-jcr-api/src/main/java/org/modeshape/jcr/api/BackupOptions.java
- modeshape-jcr-api/src/main/java/org/modeshape/jcr/api/RestoreOptions.java
- web/modeshape-web-jcr-rest-war/src/main/webapp/WEB-INF/web.xml
- web/modeshape-web-jcr-rest-war/src/test/java/org/modeshape/web/jcr/rest/ModeShapeRestServiceTest.java
- web/modeshape-web-jcr-rest/src/main/java/org/modeshape/web/jcr/rest/ModeShapeRestService.java
- web/modeshape-web-jcr-rest/src/main/java/org/modeshape/web/jcr/rest/RestHelper.java
- web/modeshape-web-jcr-rest/src/main/java/org/modeshape/web/jcr/rest/handler/RestRepositoryHandler.java
- web/modeshape-web-jcr-rest/src/main/java/org/modeshape/web/jcr/rest/handler/RestServerHandler.java
- web/modeshape-web-jcr-rest/src/main/java/org/modeshape/web/jcr/rest/model/RestException.java
- web/modeshape-web-jcr-rest/src/main/java/org/modeshape/web/jcr/rest/model/RestRepositories.java
The backup/restore methods have the following signature
```
POST http://localhost:8090/modeshape-rest/repo_name/backup 
or
POST http://localhost:8090/modeshape-rest/repo_name/backup?includeBinaries=false&documentsPerFile=1000&compress=false
```
and the response
```
{
"name": "modeshape_382GA_repo_backup_28032015_115755",
"url": "file:/d:/Work/hchiorean.jboss-integration.modeshape/web/modeshape-web-jcr-rest-war/target/modeshape_382GA_repo_backup_28032015_115755/"
}
```
The result will be placed on the server in one of the following locations (in order):
- backupLocation context param
- jboss.domain.data.dir
- jboss.server.data.dir
- user.home
and the name of the backup folder will have the pattern: `modeshape_version_repoName_backup_DDmmyyyy_HHmmss`
The restore methods have the following …
> MODE-2452 Implemented backup/restore methods for the REST service.

- deploy/jbossas/modeshape-jbossas-subsystem/src/main/java/org/modeshape/jboss/service/RepositoryService.java
I think this should be logged when problems is not empty.
> MODE-2462 log problems when they exist

- sequencers/modeshape-sequencer-teiid/src/main/java/org/modeshape/sequencer/teiid/VdbDynamicSequencer.java
- sequencers/modeshape-sequencer-teiid/src/main/java/org/modeshape/sequencer/teiid/VdbManifest.java
* VdbDynamicSequencer
* Closes the initial input stream taken from the inputProperty's
binaryValue
* VdbManifest
* Closes the XML StreamReader instance on completion of its reading
* Closing these ensures that the streams are closed and releases any locks
created on the original binary property value, avoiding the possibility
of future deadlocks when saving the property.
Is it possible to backport this to a release of 4.2.x??
> MODE-2464: Ensures all input stream in Vdb Sequencers are closed

- sequencers/modeshape-sequencer-ddl/src/main/java/org/modeshape/sequencer/ddl/DdlTokenStream.java
- sequencers/modeshape-sequencer-ddl/src/test/java/org/modeshape/sequencer/ddl/dialect/oracle/OracleDdlParserTest.java
Oracle, MySQL and postgres dialects consider a dollar sign as
a valid schema object name character. 
Table name was already handled previously but all other cases 
failed as subsection of ddl statement is created out of a list 
of tokens (at least in Oracle dialect).
Example:
Column definition like "COL$D VARCHAR2" was tokenized as
"COL", "$", "D", "VARCHAR2" and when rebuilt from tokens it
became "COL $ D VARCHAR2".
All subsequent parsing failed.
This is a generic solution.
Test result:
Tests run: 456, Failures: 0, Errors: 0, Skipped: 1
> MODE-2465 Changed DdlTokenizer to ignore "$"

- modeshape-jcr/src/main/java/org/modeshape/jcr/JcrRepository.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/JcrSession.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/NodeTypes.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/ChildReferences.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/RepositoryCache.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/RepositoryEnvironment.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/SessionCache.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/SessionCacheWrapper.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/document/AbstractChildReferences.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/document/AbstractSessionCache.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/document/DocumentTranslator.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/document/ImmutableChildReferences.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/document/MutableChildReferences.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/document/ReadOnlySessionCache.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/document/SessionChildReferences.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/document/SessionNode.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/document/WorkspaceCache.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/document/WritableSessionCache.java
- modeshape-jcr/src/test/java/org/modeshape/jcr/cache/document/AbstractSessionCacheTest.java
- modeshape-jcr/src/test/java/org/modeshape/jcr/cache/document/DocumentOptimizerTest.java
- modeshape-jcr/src/test/java/org/modeshape/jcr/cache/document/ReadOnlySessionCacheTest.java
- modeshape-jcr/src/test/java/org/modeshape/jcr/cache/document/WorkspaceCacheTest.java
- modeshape-jcr/src/test/java/org/modeshape/jcr/cache/document/WritableSessionCacheTest.java
- modeshape-jcr/src/test/java/org/modeshape/jcr/query/AbstractNodeSequenceTest.java
- modeshape-performance-tests/src/test/java/org/modeshape/test/performance/InMemoryPerformanceTest.java
The optimizations are in 2 different areas:
* the data structures being used to hold the node information - ModeShape's `MultiMap` family is heavyweight compared to the standard JDK `Maps` and doesn't require it being used in this case
* passed SNS information down to the `ChildReferences` implementations, allowing further optimizations in the way SNS indexes are computed in certain cases as well as the `Context` instance being used.
> MODE-2481 Added some more optimization to the ChildReferences implementations

- modeshape-jcr/src/main/java/org/modeshape/jcr/index/local/MapDB.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/query/BufferManager.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/query/Tuples.java
- modeshape-jcr/src/test/java/org/modeshape/jcr/JcrQueryManagerTest.java
ORDER BY col1, col2 used to cause a NullPointerException whenever col1 or col2 were nullable and indeed did contain null values. This is because the row's col1 and col2 were being serialized as a tuple, and the serialization (correctly) assumed that since a tuple was created, the sort key was non-null. However serialization of the tuple was done by serializing each component, and they +can+ be null.
Therefore, the component serializers should use a null-safe wrapper around the original serializer, see their various getSerializer() implementations. The wrapper itself is in lines 585-615. Since I guess we don't always know what serializers we have, and some serializers also leave not enough wiggle room to accomodate NULLs without violating all kinds of contracts, we have to have …
> Fix MODE-2490

- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/document/AbstractSessionCache.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/txn/NoClientTransactions.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/txn/SynchronizedTransactions.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/txn/Transactions.java
- modeshape-jcr/src/test/java/org/modeshape/jcr/TransactionsTest.java
The previous code made the incorrect assumption that a user transaction is "confined" to the thread that started it. This is obviously not the case, since the same transaction can be suspended & resumed subsequently off different threads.
> MODE-2495 Fixes how user transactions are handled

- modeshape-common/src/main/java/org/modeshape/common/text/TokenStream.java
- modeshape-common/src/test/java/org/modeshape/common/text/TokenStreamTest.java
This symbol is weird because the so-called 'capital' version (as determined by the JVM) is 'SS'. i.e. longer than the lower-case version. This sends the indexes out of kilter within the TokenStream class when using case insensitive tokenising.
The solution is to override the match method in the CaseInsensitiveToken to convert the current token to upper-case, rather than storing an upper-case version of the entire input string, which may not have the same indexes as the lower-case version.
(cherry picked from commit 9a8ac56)
> Support German Scharfes 'S' symbol when tokenising

- deploy/jbossas/modeshape-jbossas-subsystem/src/main/java/org/modeshape/jboss/service/AuthenticatorService.java
- integration/modeshape-jbossas-integration-tests/src/main/java/org/modeshape/test/integration/CustomAuthenticationProvider.java
- integration/modeshape-jbossas-integration-tests/src/main/resources/kit/jboss-wf9/standalone/configuration/standalone-modeshape.xml
- integration/modeshape-jbossas-integration-tests/src/test/java/org/modeshape/test/integration/SecurityIntegrationTest.java
This essentially makes sure that any custom providers will take precedence over the default (built-in) security providers which interface with the AS's security domain.
> MODE-2496 Makes sure custom authentication providers in the AS kit are added first in the list

- modeshape-jcr/src/main/java/org/modeshape/jcr/JcrSession.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/security/AuthorizationProvider.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/security/SecurityContext.java
The previous code would circumvent custom providers altogether, meaning that right after `session.login` any custom provider had to have assigned ModeShape-specific roles to the authenticated user in order for the login to be successful.
> MODE-2483 Allows custom authorization providers to be called for workspace based permissions

- boms/modeshape-bom-embedded/pom.xml
- modeshape-parent/pom.xml
This fixes the problem of the marshalling artifact which is now contained in the ISPN AS artifact.
> MODE-2478 Updates ISPN to 7.2.4.Final

- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/document/LazyCachedNode.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/document/WorkspaceCache.java
The code will now attempt to retry loading the parent and its references after removing it from the workspace cache first. This ensures that a "fresh" copy of the parent is always loaded from the persistent store.
> MODE-2502 Adds retrying logic when a node cannot locate its parent self-reference

- modeshape-jcr/src/main/java/org/modeshape/jcr/index/local/LocalDuplicateIndex.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/index/local/LocalEnumeratedIndex.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/index/local/LocalIndex.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/index/local/LocalIndexProvider.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/index/local/LocalMapIndex.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/index/local/LocalUniqueIndex.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/spi/index/provider/Costable.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/spi/index/provider/DefaultManagedIndex.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/spi/index/provider/IndexChangeAdapters.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/spi/index/provider/IndexProvider.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/spi/index/provider/IndexUsage.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/spi/index/provider/ManagedIndexBuilder.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/spi/index/provider/ProvidedIndex.java
- modeshape-jcr/src/test/java/org/modeshape/jcr/LocalIndexProviderTest.java
- modeshape-jcr/src/test/java/org/modeshape/jcr/index/local/AbstractLocalIndexTest.java
- modeshape-jcr/src/test/java/org/modeshape/jcr/index/local/LocalDuplicateIndexTest.java
- modeshape-jcr/src/test/java/org/modeshape/jcr/index/local/LocalUniqueIndexTest.java
Index providers are free to ignore the property if their logic does not require it (for example the Local Index provider) but other (e.g. Lucene) are interested in the property name so they can add it to the indexing information. 
Also, this PR changes the default index planning logic adding the ability for Index Providers to process multiple constraints, not just one like the `LocalIndexProvider` did.
> MODE-2159 Updates the index adapters SPI adding a property name for each add/remove operation

- modeshape-jcr/src/main/java/org/modeshape/jcr/JcrSession.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/SessionCache.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/document/WritableSessionCache.java
The fix is making sure that the version history of a node is only initialized (i.e. substructure created) __after__ the root `jcr:versionStorage` parent has been locked as part of a transaction.
> MODE-2530 Fixes the potential corruption of the version history structure for a versionable node under concurrent access

- modeshape-common/src/main/java/org/modeshape/common/util/ThreadPools.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/JcrRepository.java
- modeshape-jcr/src/test/java/org/modeshape/jcr/ConcurrentWriteTest.java
- modeshape-jcr/src/test/java/org/modeshape/jcr/JcrRepositoryStartupTest.java
- modeshape-jcr/src/test/java/org/modeshape/jcr/MultiPassAbstractTest.java
- modeshape-jcr/src/test/java/org/modeshape/jcr/RepositoryBackupAndRestoreTest.java
- modeshape-jcr/src/test/java/org/modeshape/jcr/TransactionsTest.java
- modeshape-jcr/src/test/java/org/modeshape/jcr/bus/ClusteredChangeBusTest.java
- modeshape-jcr/src/test/java/org/modeshape/jcr/value/binary/FileSystemBinaryStoreTest.java
This also updates some unit tests which failed to appropriately shut down their respective `ExecutorService` instances.
> MODE-2537-4.x Fixes the improper cleanup of components in case of an unexpected shutdown

- web/modeshape-web-explorer/src/main/java/org/modeshape/web/server/JcrServiceImpl.java
- web/modeshape-web-explorer/src/main/java/org/modeshape/web/server/impl/ConnectorImpl.java
This PR fixes bug when property with null value (ie just created node) is not displayed by property editor.
> MODE-2518: Attach binary content jcr:content

- deploy/jbossas/modeshape-jbossas-subsystem/src/main/java/org/modeshape/jboss/service/RepositoryService.java
- deploy/jbossas/modeshape-jbossas-subsystem/src/main/java/org/modeshape/jboss/subsystem/AddRepository.java
- deploy/jbossas/modeshape-jbossas-subsystem/src/main/java/org/modeshape/jboss/subsystem/Attribute.java
- deploy/jbossas/modeshape-jbossas-subsystem/src/main/java/org/modeshape/jboss/subsystem/ModeShapeSubsystemXMLReader_2_1.java
- deploy/jbossas/modeshape-jbossas-subsystem/src/main/java/org/modeshape/jboss/subsystem/ModeShapeSubsystemXMLWriter.java
- deploy/jbossas/modeshape-jbossas-subsystem/src/main/java/org/modeshape/jboss/subsystem/ModelAttributes.java
- deploy/jbossas/modeshape-jbossas-subsystem/src/main/java/org/modeshape/jboss/subsystem/ModelKeys.java
- deploy/jbossas/modeshape-jbossas-subsystem/src/main/resources/org/modeshape/jboss/subsystem/LocalDescriptions.properties
- deploy/jbossas/modeshape-jbossas-subsystem/src/main/resources/schema/modeshape_2_1.xsd
- deploy/jbossas/modeshape-jbossas-subsystem/src/test/java/org/modeshape/jboss/subsystem/ModeShapeConfigurationTest.java
- deploy/jbossas/modeshape-jbossas-subsystem/src/test/resources/org/modeshape/jboss/subsystem/modeshape-initial-content-config.xml
- deploy/jbossas/modeshape-jbossas-subsystem/src/test/resources/org/modeshape/jboss/subsystem/modeshape-node-types-config.xml
- deploy/jbossas/modeshape-jbossas-subsystem/src/test/resources/org/modeshape/jboss/subsystem/modeshape-repository-dependencies-config.xml
- integration/modeshape-jbossas-integration-tests/src/main/resources/kit/jboss-wf9/standalone/configuration/standalone-modeshape.xml
- integration/modeshape-jbossas-integration-tests/src/test/java/org/modeshape/test/integration/ExternalDependenciesIntegrationTest.java
- integration/modeshape-jbossas-integration-tests/src/test/resources/config/cars.cnd
- integration/modeshape-jbossas-integration-tests/src/test/resources/config/initial-content-cars.xml
This also introduces a more generic ability for a repository configured in WF to use the CL of another external (dependant) module when resolving configuration elements such as initial content files and node type files. 
For example, configuring a repository as:
```xml
<repository name="externalDependenciesRepository" depends-on="deployment.external-dependencies.war"/>
```
means that the repository will be able to locate & load node-types and initial content files located in the `external-dependencies.war` webapp
> MODE-2555 Adds the support of expressions to the <node-types/> WF configuration element

- sequencers/modeshape-sequencer-ddl/src/main/java/org/modeshape/sequencer/ddl/dialect/teiid/TeiidDdlConstants.java
- sequencers/modeshape-sequencer-ddl/src/test/java/org/modeshape/sequencer/ddl/dialect/teiid/TeiidDataTypeParserTest.java
Just needed to add the new GEOMETRY data type to the data type enum. No additional code needed. Wrote test to make sure the parser recognized the new data type.
> MODE-2554 Add Geometry Type to Teiid DDL dialect

- modeshape-jcr/src/main/java/org/modeshape/jcr/query/xpath/XPathParser.java
- modeshape-jcr/src/test/java/org/modeshape/jcr/JcrQueryManagerTest.java
This PR adds one more syntax checking rule for  the `XPathParser`: 
- after parsing no more tokens should remain. 
Without this check the beginning of some JCR-SQL2 statements (or even random text) will be interpreted as xpath query while remainder will be ignored. 
Web-Explorer correctly shows exception when it is fired by MS.
> MODE-2499: Executing queries from ModeShape Explorer doesn't validate dialects

- index-providers/modeshape-elasticsearch-index-provider/src/test/java/org/modeshape/jcr/index/elasticsearch/EsIndexProviderTest.java
- index-providers/modeshape-lucene-index-provider/src/main/java/org/modeshape/jcr/index/lucene/LuceneConfig.java
- index-providers/modeshape-lucene-index-provider/src/main/java/org/modeshape/jcr/index/lucene/LuceneIndex.java
- index-providers/modeshape-lucene-index-provider/src/test/java/org/modeshape/jcr/index/lucene/LuceneIndexProviderTest.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/RepositoryIndexManager.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/RepositoryQueryManager.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/spi/index/IndexFeedback.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/spi/index/provider/IndexProvider.java
- modeshape-jcr/src/test/java/org/modeshape/jcr/LocalIndexProviderTest.java
- modeshape-jcr/src/test/java/org/modeshape/jcr/cache/document/AbstractSessionCacheTest.java
- modeshape-jcr/src/test/java/org/modeshape/jcr/cache/document/WorkspaceCacheTest.java
Also, it updates the general IF_MISSING reindexing logic, so that only the indexes which actually do require reindexing are reindexed, as opposed to the all the indexes of a particular provider.
> MODE-2565 Fixes the behavior of the Lucene index provider to avoid reindexing at startup if data exists

- modeshape-jcr-api/src/main/java/org/modeshape/jcr/api/BackupOptions.java
- modeshape-jcr-api/src/main/java/org/modeshape/jcr/api/RestoreOptions.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/BackupService.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/JcrI18n.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/document/DocumentStore.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/document/LocalDocumentStore.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/federation/FederatedDocumentStore.java
- modeshape-jcr/src/main/resources/org/modeshape/jcr/JcrI18n.properties
- modeshape-jcr/src/test/resources/log4j.properties
- modeshape-performance-tests/src/test/java/org/modeshape/test/performance/FSPerformanceTest.java
- modeshape-schematic/src/main/java/org/modeshape/schematic/SchematicDb.java
- persistence/modeshape-persistence-file/src/main/java/org/modeshape/persistence/file/FileDb.java
- persistence/modeshape-persistence-relational/src/main/java/org/modeshape/persistence/relational/DefaultStatements.java
- persistence/modeshape-persistence-relational/src/main/java/org/modeshape/persistence/relational/RelationalDb.java
- persistence/modeshape-persistence-relational/src/main/java/org/modeshape/persistence/relational/Statements.java
This should fix any memory issues caused by the previous implementation, where everything was loaded and written to in one big batch.
> MODE-2587 Updates backup and restore to perform the two operations in batches

- integration/modeshape-jbossas-integration-tests/src/main/java/org/modeshape/test/integration/StartupRepositoryProvider1.java
- integration/modeshape-jbossas-integration-tests/src/main/java/org/modeshape/test/integration/StartupRepositoryProvider2.java
- integration/modeshape-jbossas-integration-tests/src/test/java/org/modeshape/test/integration/TransactionsTest.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/RepositoryCache.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/document/DocumentTranslator.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/document/LocalDocumentStore.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/query/engine/process/BufferingSequence.java
- modeshape-jcr/src/test/java/org/modeshape/jcr/ClusteredRepositoryTest.java
- modeshape-jcr/src/test/resources/config/local-index-provider-with-custom-settings.json
- persistence/modeshape-persistence-file/src/main/java/org/modeshape/persistence/file/FileDb.java
The problem in this particular case was the fact that a user transaction off a certain thread might not have been committed while  another thread was seeing the ws cache as already initialized. 
The solution was to make sure ws cache initialization takes place inside local transactions by suspending/resuming any potential outside transactions.
> MODE-2596 Fixes the concurrent initialization of the same workspace cache with user transactions

- deploy/jbossas/kit/jboss-wf/com/zaxxer/hikari/2.4.3/module.xml
- deploy/jbossas/kit/jboss-wf/org/modeshape/connector/jdbc/metadata/main/module.xml
- deploy/jbossas/kit/jboss-wf/org/modeshape/main/module.xml
- modeshape-assembly-descriptors/src/main/resources/assemblies/jboss-wf-dist.xml
- modeshape-jcr/pom.xml
- modeshape-jcr/src/main/java/org/modeshape/jcr/value/binary/Database.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/value/binary/DatabaseBinaryStore.java
This uses the same datasource implementation (Hikari) that is being used by the relational persistent storage. This artifact has also been promoted as a top-level artifact in the WF kit.
> MODE-2593 Adds datasource support to the Database Binary Store

- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/document/WorkspaceCache.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/document/WritableSessionCache.java
- modeshape-jcr/src/test/java/org/modeshape/jcr/TransactionsTest.java
The bug was caused by the fact that the transactional ws cache was being cleared after each `session.save()` call, even if  the user transaction might still not have been committed. This meant that subsequent `session.save()` calls could get/see transient changes as the "latest persisted information".
> MODE-2607 Fixes incorrect behaviour when using user transactions

- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/document/TransactionalWorkspaceCache.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/document/TransactionalWorkspaceCaches.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/document/WorkspaceCache.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/document/WritableSessionCache.java
- modeshape-jcr/src/test/java/org/modeshape/jcr/TransactionsTest.java
The bug was caused by the fact that not all the nodes were refreshed from the document store (i.e. the latest persisted version) on successive `session.save()` calls made from the same ongoing transaction
> MODE-2610 Fixes another transactional issue

- modeshape-jcr/src/main/java/org/modeshape/jcr/AbstractJcrProperty.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/JcrVersionManager.java
- modeshape-jcr/src/test/java/org/modeshape/jcr/JcrVersioningTest.java
The property should be a REFERENCE, not a STRING. The code was changed so that if the value for the property was stored as a STRING, the node to which it points can still be read back.
> MODE-2609 Fixes the type of the jcr:childVersionHistory property

- modeshape-schematic/src/main/java/org/modeshape/schematic/internal/io/BsonDataInput.java
- modeshape-schematic/src/test/java/org/modeshape/schematic/internal/document/BsonReadingAndWritingTest.java
supersedes https://github.com/ModeShape/modeshape/pull/1578 containing the same fix but with additional test cases and fewer commits.
> MODE-2615 Fixes the handling of multi-byte UTF-8 characters by the BSON reader

- modeshape-jcr/src/main/java/org/modeshape/jcr/JcrSession.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/JcrVersionManager.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/clustering/ClusteringService.java
- modeshape-jcr/src/test/java/org/modeshape/jcr/ClusteredRepositoryTest.java
Under certain timing conditions (visible especially when running in a cluster) a newly created version could be reported as not found since the events used to clear the cache are async
> MODE-2617 Fixes the cache retrieval of new versions

- modeshape-jcr/src/test/java/org/modeshape/jcr/TransactionsTest.java
- modeshape-persistence-tests/src/test/java/org/modeshape/jcr/ModeshapePersistenceIT.java
- modeshape-schematic/src/main/java/org/modeshape/schematic/SchematicDb.java
- modeshape-schematic/src/main/java/org/modeshape/schematic/SchematicEntry.java
- persistence/modeshape-persistence-file/src/main/java/org/modeshape/persistence/file/FileDb.java
- persistence/modeshape-persistence-relational/src/main/java/org/modeshape/persistence/relational/RelationalDb.java
- persistence/modeshape-persistence-relational/src/main/java/org/modeshape/persistence/relational/TransactionalCaches.java
The previous code always loaded a fresh copy of the latest persisted (i.e. successfully committed) information and did not take into account the fact that a user transaction might span multiple workspace cache usages. 
This is particularly evident when dealing with the `jcr:system` area and `SystemContent` in general, via multiple `session.save()` calls coming from different API methods.
> MODE-2623 Fixes the loading of documents from the persistent store after exclusive locks are obtained

- modeshape-jcr/src/main/java/org/modeshape/jcr/Connectors.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/ModeShapeFederationManager.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/document/DocumentStore.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/document/LocalDocumentStore.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/document/WritableSessionCache.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/federation/FederatedDocumentStore.java
This PR fixes silent exception handling of the failed transactions what causes repository inconsistency.
> MODE-2620: Method node.getParent() throws NullPointerException

- modeshape-jcr/src/main/java/org/modeshape/jcr/Connectors.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/ModeShapeFederationManager.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/document/DocumentStore.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/document/LocalDocumentStore.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/document/WritableSessionCache.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/federation/FederatedDocumentStore.java
Reverts ModeShape/modeshape#1595.
Reverted because of this build fail: https://travis-ci.org/ModeShape/modeshape/builds/162997333
> Revert "MODE-2620: Method node.getParent() throws NullPointerException"

- boms/modeshape-bom-embedded/pom.xml
- deploy/jbossas/kit/jboss-wf/org/modeshape/main/module.xml
- modeshape-assembly-descriptors/src/main/resources/assemblies/jboss-wf-dist.xml
- modeshape-jcr/pom.xml
- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/RepositoryCache.java
- modeshape-parent/pom.xml
The former is dormant and was designed for pre JDK 8 while the latter is the current active project which uses JDK 8
> MODE-2634 Replaces ConcurrentLinkedHashmap with Caffeine 2.3.3

- index-providers/modeshape-elasticsearch-index-provider/src/main/java/org/modeshape/jcr/index/elasticsearch/EsIndexProvider.java
Fix IllegalArgumentException using logger which break elasticsearch index provider usage
`java.lang.IllegalArgumentException: 1 parameter supplied, but 2 parameters required: "Elasticsearch index provider for repository '{1}' is trying to connect to cluster" => "Elasticsearch index provider for repository '{1}"
at org.modeshape.common.util.StringUtil.createString(StringUtil.java:188) ~[modeshape-common-5.2.0.Final.jar:5.2.0.Final]
at org.modeshape.common.logging.slf4j.SLF4JLoggerImpl.debug(SLF4JLoggerImpl.java:102) ~[modeshape-common-5.2.0.Final.jar:5.2.0.Final]
at org.modeshape.jcr.ExtensionLogger.debug(ExtensionLogger.java:50) ~[modeshape-jcr-5.2.0.Final.jar:5.2.0.Final]
at org.modeshape.jcr.index.elasticsearch.EsIndexProvider.doInitialize(EsIndexProvider.java:51) …
> Fix IllegalArgumentException using logger which break elasticsearch index provider usage

- modeshape-jcr/src/main/java/org/modeshape/jcr/Connectors.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/JcrSession.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/ModeShapeFederationManager.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/SessionCache.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/SessionCacheWrapper.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/document/DocumentStore.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/document/LocalDocumentStore.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/document/TransactionalWorkspaceCaches.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/document/WritableSessionCache.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/federation/FederatedDocumentStore.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/txn/Transactions.java
- modeshape-persistence-tests/src/test/java/org/modeshape/jcr/ModeshapePersistenceIT.java
This PR contains following changes:
- Pure JDBC database clean up between persistence integration tests;
- Transaction failure handling causing data lost or corruption;
- Makes creating projection atomic.
> Mode-2620-b Method node.getParent() throws NullPointerException

- modeshape-jcr/src/main/java/org/modeshape/jcr/spi/index/provider/IndexChangeAdapters.java
- modeshape-jcr/src/test/java/org/modeshape/jcr/JcrWorkspaceTest.java
- modeshape-jcr/src/test/resources/config/repo-config-local-provider-and-nodetype-index.json
PR provides fix which substitutes empty array instead of `null` as value for not assigned multiple-value property.
> MODE-2637 : NullPointerException in IndexChangeAdapter

- index-providers/modeshape-elasticsearch-index-provider/src/main/java/org/modeshape/jcr/index/elasticsearch/client/EsClient.java
- index-providers/modeshape-elasticsearch-index-provider/src/test/java/org/modeshape/jcr/index/elasticsearch/EsIndexProviderTest.java
- index-providers/modeshape-elasticsearch-index-provider/src/test/resources/config/repo-config1.json
This PR provides the fix which does not delete and the re-create existing index.
> MODE-2645 : Elasticsearch index provider always recreates index even if they exist upon engine restart

- .travis.yml
- modeshape-jcr/src/main/java/org/modeshape/jcr/AbstractJcrNode.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/JcrLockManager.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/JcrRepository.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/RepositoryCache.java
- modeshape-jcr/src/test/java/org/modeshape/jcr/JcrRepositoryTest.java
- modeshape-jcr/src/test/java/org/modeshape/jcr/TransactionsTest.java
- modeshape-parent/pom.xml
- modeshape-persistence-tests/pom.xml
This was introduced as part of https://issues.jboss.org/browse/MODE-2277 to optimize the read access of the `node#isCheckedOut` method, but the entire concept is flawed when user transactions are used. User transactions are isolated from the repository and do not trigger any notifications until the transaction is committed.
> MODE-2642 Removes the RepositoryFeaturesDetector optimization for #isCheckedOut and #isLocked

- boms/modeshape-bom-embedded/pom.xml
- deploy/jbossas/kit/jboss-wf/org/apache/tika/1.14/module.xml
- deploy/jbossas/kit/jboss-wf/org/modeshape/sequencer/pdf/main/module.xml
- extractors/modeshape-extractor-tika/src/main/java/org/modeshape/extractor/tika/TikaTextExtractor.java
- modeshape-assembly-descriptors/src/main/resources/assemblies/jboss-wf-dist.xml
- modeshape-parent/pom.xml
- sequencers/modeshape-sequencer-pdf/src/main/java/org/modeshape/sequencer/pdf/PdfBasicMetadata.java
- sequencers/modeshape-sequencer-pdf/src/main/java/org/modeshape/sequencer/pdf/PdfMetadataSequencer.java
- sequencers/modeshape-sequencer-pdf/src/test/java/org/modeshape/sequencer/pdf/PdfMetadataSequencerTest.java
The major update to PdfBox does trigger some other changes around the PDF sequencer: previous versions allowed some metadata to be extracted for encrypted PDFs, while the current version doesn't even allow reading the stream. As such, the behavior of the sequencer has been updated to reflect this.
> MODE-2648 Upgrades Apache Tika to 1.14 and PdfBox to 2.0.3 to avoid CVEs

- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/document/DocumentTranslator.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/document/SessionNode.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/document/WritableSessionCache.java
- modeshape-jcr/src/test/java/org/modeshape/jcr/JcrLockManagerTest.java
As per `JCR #17.7` locked nodes should be copied without any special restriction
> MODE-2654 Fixes the behavior of copying locked nodes

- modeshape-jcr/src/main/java/org/modeshape/jcr/RepositoryLockManager.java
This addresses potential multi-threaded deadlocks (in a cluster) in the sense that the same order of node keys should be used when locking nodes internally across the JCR `lock` and `unlock` operations, as a whole.
> MODE-2665 Changes the RepositoryLockManager#unlock method so that it saves the system session first

- modeshape-jcr/src/main/java/org/modeshape/jcr/query/Tuples.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/query/plan/CanonicalPlanner.java
- modeshape-jcr/src/test/java/org/modeshape/jcr/JcrQueryManagerTest.java
This commit also makes sure that when ORDER BY is used with the same column multiple times, only one occurrence is present in the query plan
> MODE-2666 Fixes the issue of the Comparators used for MapDB storage not being Serializable

- modeshape-jcr/src/main/java/org/modeshape/jcr/JcrI18n.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/document/AbstractSessionCache.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/document/ReadOnlySessionCache.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/document/WritableSessionCache.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/txn/LocalTransaction.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/txn/Transactions.java
- modeshape-jcr/src/main/resources/org/modeshape/jcr/JcrI18n.properties
- modeshape-jcr/src/test/java/org/modeshape/jcr/TransactionsTest.java
Any JCR session operation attempted within a non active user transaction will raise an exception and will leave the transient state of the session unchanged (as per the docs of the session.save method)
> MODE-2668 Fixes the handling of JCR operations within non-active user transactions

- deploy/jbossas/modeshape-jbossas-subsystem/src/main/java/org/modeshape/jboss/subsystem/AddS3BinaryStorage.java
- deploy/jbossas/modeshape-jbossas-subsystem/src/main/java/org/modeshape/jboss/subsystem/Attribute.java
- deploy/jbossas/modeshape-jbossas-subsystem/src/main/java/org/modeshape/jboss/subsystem/ModeShapeSubsystemXMLReader_3_0.java
- deploy/jbossas/modeshape-jbossas-subsystem/src/main/java/org/modeshape/jboss/subsystem/ModeShapeSubsystemXMLWriter.java
- deploy/jbossas/modeshape-jbossas-subsystem/src/main/java/org/modeshape/jboss/subsystem/ModelAttributes.java
- deploy/jbossas/modeshape-jbossas-subsystem/src/main/resources/org/modeshape/jboss/subsystem/LocalDescriptions.properties
- deploy/jbossas/modeshape-jbossas-subsystem/src/main/resources/schema/modeshape_3_0.xsd
- deploy/jbossas/modeshape-jbossas-subsystem/src/test/resources/org/modeshape/jboss/subsystem/modeshape-s3-compatible-storage.xml
- modeshape-jcr/src/main/java/org/modeshape/jcr/RepositoryConfiguration.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/value/binary/S3BinaryStore.java
- modeshape-jcr/src/main/resources/org/modeshape/jcr/repository-config-schema.json
Added changes to:
-Added additional overloaded  constructor to take 'endpoint' as an parameter
-Updated schema file to support this additional parameter (as optional to keep backward compatibility).
-Repository config files so it uses endpoint
{
"name": "Test Repository",
"storage": {
"binaryStorage": {
"type": "s3",
"username": "access_key",
"password": "secrey",
"bucketName": "modeshape_bucket",
"endPoint": "https://some3scompatiblestorage"
}
}
}
> MODE-2667, Added S3 endpoint support

- modeshape-jcr/src/main/java/org/modeshape/jcr/txn/Transactions.java
- modeshape-jcr/src/main/resources/org/modeshape/jcr/JcrI18n.properties
- persistence/modeshape-persistence-relational/src/main/java/org/modeshape/persistence/relational/RelationalDb.java
- persistence/modeshape-persistence-relational/src/main/java/org/modeshape/persistence/relational/TransactionalCaches.java
- persistence/modeshape-persistence-relational/src/main/java/org/modeshape/persistence/relational/TransactionsHolder.java
The change for https://issues.jboss.org/browse/MODE-2668 detects aborted user transactions when the equivalent ModeShape transaction is being searched
The change for https://issues.jboss.org/browse/MODE-2669 allows the relational DB provider to correctly clean up resources even if commit or rollback are called from different threads
> MODE-2668, MODE-2669 Fixes some more issues around user transactions

- modeshape-jcr/src/main/java/org/modeshape/jcr/InitialContentImporter.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/JcrRepository.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/ModeShapeLexicon.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/RepositoryCache.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/document/LocalDocumentStore.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/locking/AbstractLockingService.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/locking/JGroupsLockingService.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/locking/StandaloneLockingService.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/txn/Transactions.java
- modeshape-jcr/src/test/java/org/modeshape/jcr/JcrQueryManagerTest.java
- modeshape-jcr/src/test/java/org/modeshape/jcr/TestingUtil.java
- modeshape-jcr/src/test/java/org/modeshape/jcr/TransactionsTest.java
- modeshape-jcr/src/test/java/org/modeshape/jcr/locking/StandaloneLockingServiceTest.java
- modeshape-jcr/src/test/resources/config/repo-config-db-txn.json
- persistence/modeshape-persistence-file/src/main/java/org/modeshape/persistence/file/FileDb.java
- persistence/modeshape-persistence-relational/src/main/java/org/modeshape/persistence/relational/RelationalDb.java
- persistence/modeshape-persistence-relational/src/main/java/org/modeshape/persistence/relational/RelationalProviderException.java
- persistence/modeshape-persistence-relational/src/main/java/org/modeshape/persistence/relational/TransactionalCaches.java
- persistence/modeshape-persistence-relational/src/main/java/org/modeshape/persistence/relational/TransactionsHolder.java
- persistence/modeshape-persistence-relational/src/main/resources/org/modeshape/persistence/relational/RelationalProviderI18n.properties
The new lock implementation uses a bare-bone `AbstractQueuedSynchronizer` implementation because in ModeShape's case locks have to be able to be unlocked from other threads than the owning threads (transaction rollbacks). The previous `ReentrantLock` implementation would obviously not work.
This commit also changes the way the persistence stores deal with transactions: instead of holding onto the "current" transaction via a `ThreadLocal` variable, they will now rely on their internal mapping of tx ids. This is provided by ModeShape for each transaction. Therefore, thread-locality is no longer an issue.
The commit further changes some of the ways in which internal transactions are used during repository startup, making sure some operations are grouped and some - the preconfigured …
> MODE-2670 Changes the implementation of the internal repository locking

- integration/modeshape-jbossas-integration-tests/src/test/java/org/modeshape/test/integration/ClusteredConfigurationIntegrationTest.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/JcrI18n.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/JcrRepository.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/RepositoryConfiguration.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/RepositoryCache.java
- modeshape-jcr/src/main/resources/org/modeshape/jcr/JcrI18n.properties
- modeshape-jcr/src/test/java/org/modeshape/jcr/TransactionsTest.java
- modeshape-jcr/src/test/java/org/modeshape/jcr/bus/AbstractChangeBusTest.java
- modeshape-jcr/src/test/java/org/modeshape/jcr/bus/ClusteredChangeBusTest.java
- modeshape-schematic/src/main/java/org/modeshape/schematic/document/Document.java
- modeshape-schematic/src/main/java/org/modeshape/schematic/internal/document/ArrayEditor.java
- modeshape-schematic/src/main/java/org/modeshape/schematic/internal/document/BasicArray.java
- modeshape-schematic/src/main/java/org/modeshape/schematic/internal/document/BasicDocument.java
- modeshape-schematic/src/main/java/org/modeshape/schematic/internal/document/DocumentEditor.java
This commit also changes the default locking method in a cluster to be DB locking, which is far more reliable than JGroups. That latter has been deprecated (code wise) and will be removed in the next major version.
> MODE-2670 Changes the logic of initializing in a cluster, removing redundant locking

- persistence/modeshape-persistence-relational/src/main/java/org/modeshape/persistence/relational/RelationalDb.java
Adding a name of the current thread may be a bit redundant, since logger can be typically configured to provide the name of the thread in which a given event was triggered, however, it certainly does not hurt to be a bit more verbose in this particular case.
> MODE-2673: add missing argument to [threadAssociatedWithAnotherTransaction] i18n key.

- modeshape-jcr/src/main/java/org/modeshape/connector/filesystem/LegacySidecarExtraPropertyStore.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/AbstractJcrNode.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/JcrSession.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/JcrSharedNodeCache.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/JcrVersionHistoryNode.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/cache/document/WritableSessionCache.java
- modeshape-jcr/src/test/java/org/modeshape/jcr/SequencingTest.java
- modeshape-jcr/src/test/java/org/modeshape/jcr/ShareableNodesTest.java
- persistence/modeshape-persistence-relational/src/main/java/org/modeshape/persistence/relational/DefaultStatements.java
- persistence/modeshape-persistence-relational/src/main/java/org/modeshape/persistence/relational/RelationalDb.java
- persistence/modeshape-persistence-relational/src/main/java/org/modeshape/persistence/relational/Statements.java
The problem was that the `RelationalDb` was incorrectly sending back a "dummy" document which had no ID causing subsequent failures.
This commit contains an additional (unrelated) change which clears the internal `JcrSession` state after a successful `save` or `refresh`. This should ensure better memory handling as it does not keep "hydrated" JCR node references in the internal cache
> MODE-2672 Fixes the handling of node removals spanning multiple session saves via the same user transaction

- modeshape-jcr/src/main/java/org/modeshape/jcr/value/binary/DatabaseBinaryStore.java
- modeshape-jcr/src/test/java/org/modeshape/jcr/value/binary/DatabaseBinaryStoreTest.java
It also fixes the case of multiple cluster nodes inserting the same binary simultaneously in the database.
> MODE-2678 Changes the DatabaseBinaryStore to use  transactions instead of auto-committed connections

- index-providers/modeshape-lucene-index-provider/src/main/java/org/modeshape/jcr/index/lucene/query/CompareStringQuery.java
- index-providers/modeshape-lucene-index-provider/src/main/java/org/modeshape/jcr/index/lucene/query/LuceneQueryFactory.java
- index-providers/modeshape-lucene-index-provider/src/main/java/org/modeshape/jcr/index/lucene/query/RegexQuery.java
- index-providers/modeshape-lucene-index-provider/src/test/java/org/modeshape/jcr/index/lucene/LuceneIndexProviderTest.java
Note that since Lucene 6, the old Jakarta-based `RegexQuery` is no longer present and therefore the previous code used Lucene's `RegexpQuery` which does not support case insensitive searching. This commit fixes the issue by using a custom query.
> MODE-2683 Fixes the behavior of Regex queries for the Lucene Index Provider

- deploy/jbossas/kit/jboss-wf/org/modeshape/main/module.xml
- extractors/modeshape-extractor-tika/src/test/java/org/modeshape/extractor/tika/TikaTextExtractorTest.java
- modeshape-jcr/pom.xml
- modeshape-jcr/src/main/java/org/modeshape/jcr/RepositoryConfiguration.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/mimetype/DefaultMimeTypeDetector.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/mimetype/MimeTypeDetectors.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/mimetype/tika/TikaContentDetector.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/mimetype/tika/TikaMimeTypeDetector.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/mimetype/tika/TikaNameOnlyDetector.java
- modeshape-jcr/src/main/resources/org/modeshape/jcr/mimetype/mimetypes.properties
- modeshape-jcr/src/test/java/org/modeshape/jcr/mimetype/DefaultMimeTypeDetectorTest.java
- modeshape-jcr/src/test/java/org/modeshape/jcr/mimetype/MimeTypeDetectorsTest.java
- modeshape-jcr/src/test/java/org/modeshape/jcr/mimetype/tika/ContentDetectorTest.java
- modeshape-jcr/src/test/java/org/modeshape/jcr/mimetype/tika/NameOnlyDetectorTest.java
- modeshape-jcr/src/test/java/org/modeshape/jcr/value/binary/AbstractBinaryStoreTest.java
- sequencers/modeshape-sequencer-audio/src/main/java/org/modeshape/sequencer/audio/AudioMetadata.java
- sequencers/modeshape-sequencer-audio/src/test/java/org/modeshape/sequencer/audio/AudioMetadataSequencerTest.java
- web/modeshape-web-cmis-war/src/test/java/org/modeshape/cmis/ModeShapeCmisClientTest.java
- web/modeshape-web-jcr-rest-war/src/test/java/org/modeshape/web/jcr/rest/ModeShapeRestServiceTest.java
The mime type extraction functionality will still function as-is if Tika is present, but now there is also an independent extension-based default which will be used if Tika is not present in the CP at runtime
> MODE-2684 Removes the compile time dependency of modeshape-core towards Apache Tika

- deploy/jbossas/modeshape-jbossas-subsystem/src/main/java/org/modeshape/jboss/subsystem/AddS3BinaryStorage.java
- deploy/jbossas/modeshape-jbossas-subsystem/src/main/java/org/modeshape/jboss/subsystem/ModelAttributes.java
- deploy/jbossas/modeshape-jbossas-subsystem/src/test/resources/org/modeshape/jboss/subsystem/modeshape-s3-binary-storage.xml
- modeshape-jcr/src/main/java/org/modeshape/jcr/RepositoryConfiguration.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/value/binary/S3BinaryStore.java
- modeshape-jcr/src/main/resources/org/modeshape/jcr/repository-config-schema.json
https://issues.jboss.org/browse/MODE-2693
> Support using profile-based credentials for S3 binary storage

- index-providers/modeshape-lucene-index-provider/src/main/java/org/modeshape/jcr/index/lucene/query/CompareStringQuery.java
- index-providers/modeshape-lucene-index-provider/src/test/java/org/modeshape/jcr/index/lucene/SingleColumnIndexSearchTest.java
- modeshape-jcr/src/main/java/org/modeshape/jcr/query/engine/QueryUtil.java
> MODE-2720 Lucene index provider does not correctly handle LIKE constraints containing a backslash

- modeshape-jcr/src/main/java/org/modeshape/jcr/value/binary/S3BinaryStore.java
Binary value must be marked as "used" (unused=false) when storing in fileSystemCache (no matter what is value of "markAsUnused"). In following case it can be crucial:
If couple of threads are trying to add different files in same S3BinaryStore at same time, they will store files in the same fileSystemCache, and when some thread finish, it will delete all files marked as unused from cache (that will be all files stored in cache from another threads), and exception: 
org.modeshape.jcr.value.binary.BinaryStoreException: Unable to find binary value with key "78ed7457b289ba42ff67256f33a88b5bf0ca3012" within binary store at "/tmp/modeshape-binary-store"
at org.modeshape.jcr.value.binary.S3BinaryStore.storeValue(S3BinaryStore.java:251)
at …
> Fix parallel uploading in Amazon S3
